# Generated by Django 5.1.5 on 2025-02-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interests',
            name='room_name',
            field=models.CharField(default='null', max_length=255, unique=True),
        ),
    ]
