# Generated by Django 5.1.5 on 2025-02-04 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_interests_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='user2',
        ),
    ]
